// GENERATED by gen-relation-tags.mjs - do not edit by hand.
//
// PostGraphile v4's simplify inflector only simplified FK relation names when
// the referencing column ended in exactly "Id"; the v5 simplify-inflection
// preset simplifies more aggressively (bondDid, class, collection, ...). To
// keep every relation field byte-identical to the deployed v4 API, this file
// pins each remaining FK constraint to the relation names read out of the v4
// SDL. The *Exists filter fields and related orderBy/filter type names derive
// from these, so they stay v4-compatible too.
export const RELATION_COMPAT_CONSTRAINT_TAGS = {
  "public.BondAlpha.BondAlpha_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "bondAlphasByBondDid" },
  },
  "public.BondBuy.BondBuy_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "bondBuysByBondDid" },
  },
  "public.BondSell.BondSell_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "bondSellsByBondDid" },
  },
  "public.BondSwap.BondSwap_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "bondSwapsByBondDid" },
  },
  "public.Claim.Claim_collectionId_fkey": {
    tags: { foreignFieldName: "claimsByCollectionId" },
  },
  "public.dao_core_item.dao_core_item_dao_address_fkey": {
    tags: { fieldName: "daoCoreByDaoAddress", foreignFieldName: "daoCoreItemsByDaoAddress" },
  },
  "public.dao_core.dao_core_voting_module_fkey": {
    tags: { fieldName: "daoVotingModuleByVotingModule", foreignFieldName: "daoCoresByVotingModule" },
  },
  "public.dao_cw20_staker.dao_cw20_staker_staking_contract_fkey": {
    tags: { fieldName: "daoCw20StakingContractByStakingContract", foreignFieldName: "daoCw20StakersByStakingContract" },
  },
  "public.dao_cw4_member.dao_cw4_member_group_contract_address_fkey": {
    tags: { fieldName: "daoCw4GroupContractByGroupContractAddress", foreignFieldName: "daoCw4MembersByGroupContractAddress" },
  },
  "public.dao_cw721_staker.dao_cw721_staker_voting_module_address_fkey": {
    tags: { fieldName: "daoVotingModuleByVotingModuleAddress", foreignFieldName: "daoCw721StakersByVotingModuleAddress" },
  },
  "public.dao_native_staker.dao_native_staker_voting_module_address_fkey": {
    tags: { fieldName: "daoVotingModuleByVotingModuleAddress", foreignFieldName: "daoNativeStakersByVotingModuleAddress" },
  },
  "public.dao_pre_propose_approval.dao_pre_propose_approval_pre_propose_module_fkey": {
    tags: { fieldName: "daoPreProposeModuleByPreProposeModule", foreignFieldName: "daoPreProposeApprovalsByPreProposeModule" },
  },
  "public.dao_proposal_hook.dao_proposal_hook_proposal_module_fkey": {
    tags: { fieldName: "daoProposalModuleByProposalModule", foreignFieldName: "daoProposalHooksByProposalModule" },
  },
  "public.dao_proposal_module.dao_proposal_module_dao_address_fkey": {
    tags: { fieldName: "daoCoreByDaoAddress", foreignFieldName: "daoProposalModulesByDaoAddress" },
  },
  "public.dao_proposal_module.dao_proposal_module_pre_propose_module_fkey": {
    tags: { fieldName: "daoPreProposeModuleByPreProposeModule", foreignFieldName: "daoProposalModulesByPreProposeModule" },
  },
  "public.dao_proposal.dao_proposal_proposal_module_fkey": {
    tags: { fieldName: "daoProposalModuleByProposalModule", foreignFieldName: "daoProposalsByProposalModule" },
  },
  "public.dao_sub_dao.dao_sub_dao_dao_address_fkey": {
    tags: { fieldName: "daoCoreByDaoAddress", foreignFieldName: "daoSubDaosByDaoAddress" },
  },
  "public.dao_vote_hook.dao_vote_hook_proposal_module_fkey": {
    tags: { fieldName: "daoProposalModuleByProposalModule", foreignFieldName: "daoVoteHooksByProposalModule" },
  },
  "public.dao_vote.dao_vote_proposal_module_proposal_id_fkey": {
    tags: { fieldName: "daoProposalByProposalModuleAndProposalId", foreignFieldName: "daoVotesByProposalModuleAndProposalId" },
  },
  "public.Entity.Entity_id_fkey": {
    tags: { fieldName: "iidById", foreignFieldName: "entityById" },
  },
  "public.epoch_event.epoch_event_epoch_identifier_fkey": {
    tags: { fieldName: "epochByEpochIdentifier", foreignFieldName: "epochEventsByEpochIdentifier" },
  },
  "public.Evaluation.Evaluation_claimId_fkey": {
    tags: { foreignFieldName: "evaluationsByClaimId" },
  },
  "public.dao_voting_module.fk_voting_module_group_contract": {
    tags: { fieldName: "daoCw4GroupContractByGroupContractAddress", foreignFieldName: "daoVotingModulesByGroupContractAddress" },
  },
  "public.dao_voting_module.fk_voting_module_staking_contract": {
    tags: { fieldName: "daoCw20StakingContractByStakingContract", foreignFieldName: "daoVotingModulesByStakingContract" },
  },
  "public.ixo_swap_price_history.ixo_swap_price_history_address_fkey": {
    tags: { fieldName: "ixoSwapByAddress", foreignFieldName: "ixoSwapPriceHistoriesByAddress" },
  },
  "public.OutcomePayment.OutcomePayment_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "outcomePaymentsByBondDid" },
  },
  "public.ReserveWithdrawal.ReserveWithdrawal_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "reserveWithdrawalsByBondDid" },
  },
  "public.ShareWithdrawal.ShareWithdrawal_bondDid_fkey": {
    tags: { fieldName: "bondByBondDid", foreignFieldName: "shareWithdrawalsByBondDid" },
  },
  "public.Token.Token_collection_fkey": {
    tags: { fieldName: "entityByCollection", foreignFieldName: "tokensByCollection" },
  },
  "public.Token.Token_name_fkey": {
    tags: { fieldName: "tokenClassByName", foreignFieldName: "tokensByName" },
  },
  "public.TokenBalance.TokenBalance_tokenId_fkey": {
    tags: { foreignFieldName: "tokenBalancesByTokenId" },
  },
  "public.TokenCancelled.TokenCancelled_name_fkey": {
    tags: { fieldName: "tokenClassByName", foreignFieldName: "tokenCancelledsByName" },
  },
  "public.TokenClass.TokenClass_class_fkey": {
    tags: { fieldName: "entityByClass", foreignFieldName: "tokenClassesByClass" },
  },
  "public.TokenData.TokenData_tokenId_fkey": {
    tags: { foreignFieldName: "tokenDataByTokenId" },
  },
  "public.TokenRetired.TokenRetired_id_fkey": {
    tags: { fieldName: "tokenById", foreignFieldName: "tokenRetiredsById" },
  },
  "public.TokenRetired.TokenRetired_name_fkey": {
    tags: { fieldName: "tokenClassByName", foreignFieldName: "tokenRetiredsByName" },
  },
  "public.TokenTransaction.TokenTransaction_tokenId_fkey": {
    tags: { foreignFieldName: "tokenTransactionsByTokenId" },
  },
  "public.TransactionSigner.TransactionSigner_authenticatorId_fkey": {
    tags: { foreignFieldName: "transactionSignersByAuthenticatorId" },
  },
  "public.TransactionSigner.TransactionSigner_transactionHash_fkey": {
    tags: { foreignFieldName: "transactionSignersByTransactionId" },
  },
} as const;
